<option value="01" {if $month == 1}selected{/if}>January</option>
<option value="02" {if $month == 2}selected{/if}>February</option>
<option value="03" {if $month == 3}selected{/if}>March</option>
<option value="04" {if $month == 4}selected{/if}>April</option>
<option value="05" {if $month == 5}selected{/if}>May</option>
<option value="06" {if $month == 6}selected{/if}>June</option>
<option value="07" {if $month == 7}selected{/if}>July</option>
<option value="08" {if $month == 8}selected{/if}>August</option>
<option value="09" {if $month == 9}selected{/if}>September</option>
<option value="10" {if $month == 10}selected{/if}>October</option>
<option value="11" {if $month == 11}selected{/if}>November</option>
<option value="12" {if $month == 12}selected{/if}>December</option>